export const environment = {
  production: false,
  installedInstances: ['asean', 'botswana', 'bhutan', 'ipas'],
  env: 'awsAcc',
  appUrl: 'http://localhost:4200',
  backendUrl: 'http://localhost:3005',
};

export const configuration = {
  default: {
    module: {
      edms: true,
      patents: true,
      designs: true,
      trademarks: true,
      datacoverage: true,
      gidatabase: true,
      portfolios: true,
    },
    order: ['patents', 'designs', 'trademarks', 'gidatabase', 'portfolios'],
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    officeInfo: {
      fullName: 'WIPO IP Portal',
      shortName: 'WIPO',
      logoPath: 'assets/images/logos/default-logo.png',
      mainColor: '#0067c0',
    },
    theme: {
      preset: 'Aura',
      primary: 'blue',
      surface: 'slate',
      darkTheme: false,
    },
  },
  asean: {
    module: {
      edms: true,
      patents: true,
      designs: true,
      trademarks: true,
      datacoverage: true,
      gidatabase: true,
      portfolios: true,
    },
    order: ['patents', 'designs', 'trademarks', 'gidatabase', 'portfolios'],
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
    officeInfo: {
      fullName: 'ASEAN IP Portal',
      shortName: 'ASEAN',
      logoPath: 'assets/images/logos/asean-logo.png',
      mainColor: '#78b96b',
    },
    theme: {
      preset: 'ModernNature',
      primary: 'green',
      surface: 'slate',
      darkTheme: false,
    },
  },
  botswana: {
    module: {
      edms: true,
      patents: true,
      designs: true,
      trademarks: true,
      datacoverage: false,
      gidatabase: false,
      portfolios: true,
    },
    order: ['patents', 'designs', 'trademarks', 'portfolios'],
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    officeInfo: {
      fullName: 'Botswana Online Filing',
      shortName: 'BOFI',
      logoPath: 'assets/images/logos/botswana-logo.png',
      mainColor: '#60a5fa',
    },
    theme: {
      preset: 'Lara',
      primary: 'blue',
      surface: 'neutral',
      darkTheme: false,
    },
  },
  bhutan: {
    module: {
      edms: true,
      patents: true,
      designs: true,
      trademarks: true,
      datacoverage: false,
      gidatabase: false,
      portfolios: true,
    },
    order: ['patents', 'designs', 'trademarks', 'portfolios'],
    availableLangs: ['en', 'dz'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    officeInfo: {
      fullName: 'Bhutan Online Filing',
      shortName: 'BHFI',
      logoPath: 'assets/images/logos/bhutan-logo.png',
      mainColor: '#f472b6',
    },
    theme: {
      preset: 'Material',
      primary: 'pink',
      surface: 'slate',
      darkTheme: false,
    },
  },
  ipas: {
    module: {
      edms: true,
      patents: true,
      designs: true,
      trademarks: true,
      datacoverage: true,
      gidatabase: true,
      portfolios: true,
    },
    order: ['patents', 'designs', 'trademarks', 'gidatabase', 'portfolios'],
    availableLangs: ['en', 'fr', 'es', 'ar', 'zh'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    officeInfo: {
      fullName: 'WIPO IPAS',
      shortName: 'IPAS',
      logoPath: 'assets/images/logos/ipas-logo.png',
      mainColor: '#0067c0',
    },
    theme: {
      preset: 'WipoTheme',
      primary: 'blue',
      surface: 'slate',
      darkTheme: false,
    },
  },
};
